from .treino import preparar_treino_classe_secundaria, executar_treino_classe_secundaria
from .forja import executar_forja_prototipo, executar_forja_machadinha
from .construcao import construir_estrutura
from .melhorias import melhorar_estrutura
from .producao import preparar_configuracao_producao, definir_plano_producao
