from . import combate
from . import crafting
from . import dungeons
from . import economia
from . import evolucao
from . import interacoes
from . import loja
from . import loot
from . import meta
from . import progressao
from . import quests
from . import reputacao
from . import tempo
from . import worldgen
